	discovery.docker "flog_scrape" {
		host             = "unix:///var/run/docker.sock"
		refresh_interval = "5s"
	}
		
		discovery.relabel "flog_scrape" {
		targets = discovery.docker.flog_scrape.targets
		
		rule {
		source_labels = ["__meta_docker_container_name"]
		regex         = "/(.*)"
		target_label  = "container"
		}
		
		rule {
		source_labels = ["__meta_docker_container_name"]
		target_label  = "job"
		}
		
		rule {
		source_labels = ["__meta_docker_image_name"]
		target_label  = "image"
		}
	}
		
		loki.source.docker "flog_scrape" {
		host             = "unix:///var/run/docker.sock"
		targets          = discovery.relabel.flog_scrape.output  
		forward_to       = [loki.write.default.receiver]
	}
		
		loki.write "default" {
		endpoint {
		url       = "http://gateway:3100/loki/api/v1/push"
		tenant_id = "tenant1"
		}
	}